### ISSUE TITLE
TypeError: this._listener.remove is not a function

### ISSUE THREAD

**Issue by moimikey** [iamdustan/yellowbox-react#6]
```
this._listener.remove is not a function
TypeError: this._listener.remove is not a function
    at YellowBox.componentWillUnmount (http://localhost:8001/static/preview.bundle.js:42924:24)
    at unmountComponent (http://localhost:8001/static/preview.bundle.js:12022:55)
    at recollectNodeTree (http://localhost:8001/static/preview.bundle.js:11879:24)
    at unmountComponent (http://localhost:8001/static/preview.bundle.js:12033:40)
    at recollectNodeTree (http://localhost:8001/static/preview.bundle.js:11879:24)
    at unmountComponent (http://localhost:8001/static/preview.bundle.js:12033:40)
    at buildComponentFromVNode (http://localhost:8001/static/preview.bundle.js:12001:17)
    at idiff (http://localhost:8001/static/preview.bundle.js:11814:48)
    at diff (http://localhost:8001/static/preview.bundle.js:11793:19)
    at Object.render (http://localhost:8001/static/preview.bundle.js:12045:16)
```

I tried implementing this in `react-storybook` as a decorator. In `react-storybook` you're presented a navigable page, comprised of component examples. when you change pages, components will unmount. I got this error on unmount. Maybe it's my implementation, otherwise something related to how YellowBox unmounts.

**Comment by iamdustan** [comment]
A decorator as in an ESFuture decorator? If you can provide a minimal snippet of the implementing code I’ll have a much better chance of helping.
